INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('1', 'First User', 'First Age', '30000');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('2', 'Second User', 'Second Age', '20000');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('3', 'Third User', 'Third Age', '15000');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('4', 'Fourth User', 'Fourth Age', '25000');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('5', 'Fifth User', 'Fifth Age', '80000');
INSERT INTO USERMANAGER.USERS (ID, USER_NAME, USER_AGE, USER_SEX) VALUES ('6', 'Sixth User', 'Sixth Age', '50000');
